# Generated by Django 3.2.6 on 2023-04-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('channelKey', models.CharField(max_length=200)),
                ('numberOfEpisode', models.IntegerField()),
                ('register_date', models.DateTimeField()),
                ('creator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('time_span', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('image', models.CharField(max_length=100)),
                ('podcast_name', models.CharField(max_length=150)),
                ('guid', models.CharField(max_length=30)),
                ('creator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
